learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ll_app.urls'))
]

ll_app/urls.py
"""Defines URL pattern for ll_app"""

from django.urls import path
from . import views

app_name = "ll_app"

urlpatterns = [
    
    #Home page
    path('', views.index, name='index'),

    #Topics page
    path('topics/', views.topics, name='topics'),

    #Entry page
    path('topics/<int:topic_id>', views.topic, name='topic')
]

ll_app/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model"""
        return self.text
    
class Entry(models.Model):
    """Entry made by a user under a topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):
        """Return a string representation of the model"""
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return f"{self.text}"

ll_app/views.py
from django.shortcuts import render
from .models import Topic

# Create your views here.
def index(request):
    """The home page for ll_app"""
    return render(request, 'll_app/index.html')

def topics(request):
    """The Home page for all topics"""
    topics = Topic.objects.order_by('date_added')
    context = {'topics':topics}
    return render(request, 'll_app/topics.html', context)

def topic(request,topic_id):
    """The home page for entry"""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'll_app/topic.html', context)

ll_app/templates/ll_app/base.html
<p>
    <a href="{% url 'll_app:index' %}">Learning Log</a> -
    <a href="{% url 'll_app:topics' %}">Topics</a>
</p>

{% block content %}{% endblock content %}

ll_app/templates/ll_app/index.html
{% extends 'll_app/base.html' %}

{% block content %}
<p>Learning log helps you keep track of your learning, for any topic you're learning about.</p>
{% endblock content %}

ll_app/templates/ll_app/topic.html
{% extends 'll_app/base.html' %}

{% block content %}

<p>{{topic}}</p>
<p>Entries:</p>
<ul>
    {% for entry in entries %}
    <li>
        <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
        <p>{{ entry.text|linebreaks }}</p>
    </li>
    {% empty %}
    <li>No entries added for the topic yet.</li>
    {% endfor %}
</ul>
{% endblock content %}

ll_app/templates/ll_app/topics.html
{% extends 'll_app/base.html' %}

{% block content %}

<ul>
    {% for topic in topics %}
    <li>
        <a href="{% url 'll_app:topic' topic.id %}">{{topic}}</a>
    </li>
    {% empty %}
    <li>No topics have been added yet.</li>
    {% endfor %}
</ul>

{% endblock content %}